export enum ENUM_BOOKING_REF_TYPE {
    IN_APP_MEETING = 'IN_APP_MEETING',
    EXTERNAL_MEETING = 'EXTERNAL_MEETING',
}

export enum ENUM_BOOKING_STATUS_TYPE {
    PENDING = 'PENDING',
    ACCEPTED = 'ACCEPTED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED',
}
