export enum ENUM_USER_SIGN_UP_FROM {
    ADMIN = 'ADMIN',
    PUBLIC = 'PUBLIC',
    SEED = 'SEED',
}

export enum ENUM_USER_STATUS {
    CREATED = 'CREATED',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    DELETED = 'DELETED',
    BLOCKED = 'BLOCKED',
}

export enum ENUM_USER_GENDER {
    MALE = 'MALE',
    FEMALE = 'FEMALE',
}

export enum ENUM_USER_AVAILABILITY_TIMESLOTS {
    MINUTES_15 = 'MINUTES_15',
    MINUTES_30 = 'MINUTES_30',
    MINUTES_45 = 'MINUTES_45',
    MINUTES_60 = 'MINUTES_60',
}
