name: Linter
on:
    workflow_dispatch:
    pull_request:
        branches:
          - main
          - development

jobs:
    linter:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['lts/*']

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Setup node version ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn --frozen-lockfile --non-interactive

            - name: Linter
              run: yarn lint
