name: Test
on:
    workflow_dispatch:
    # pull_request:
    #     branches:
    #       - main
    #       - development

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: ['lts/*']

        steps:
            - name: Git checkout
              uses: actions/checkout@v4

            - name: Setup node version ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn --frozen-lockfile --non-interactive

            - name: Unit Test
              run: NODE_ENV=test yarn test
              env:
                  CI: true
